spring.application.name=clai
# Importar variaveis de ambiente do .env, funciona com as do shell também.
spring.config.import=optional:file:.env[.properties]

# Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/clai_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Otimização do Pool de Conexões
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Segurar a conexao com o banco (nao necessario para nosso caso agora)
# spring.jpa.open-in-view=false

# Otimização de busca em lote
spring.jpa.properties.hibernate.default_batch_fetch_size=100